spring.application.name=profile-service
server.port=9214

spring.r2dbc.url=r2dbc:mysql://localhost:3307/profile_db
spring.r2dbc.username=root
spring.r2dbc.password=123456

spring.sql.init.mode=never

spring.liquibase.enabled=true
spring.liquibase.url=jdbc:mysql://localhost:3307/profile_db
spring.liquibase.user=root
spring.liquibase.password=123456
spring.liquibase.change-log=classpath:/db/changelog/db.changelog-master.xml
logging.level.liquibase=INFO